include $(ROOT_DIR)/clear.mk
TARGET		:=picture
START_OBJ	:=start.o
OBJS		:=clock.o ddr.o nand.o led.o boot.o main.o uart.o irq.o ac97.o lcd.o key.o touch.o wdt.o
ADDR		:=0x57000000
include $(ROOT_DIR)/rule.mk
